name: Validate PR Title

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate PR title
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          echo "PR title: $pr_title"

          # pattern for  PR title
          pattern="^CREDMGR-[0-9]+ .+$"

          # Check if PR title matches the required pattern
          if [[ ! "$pr_title" =~ $pattern ]]; then
            echo "PR title '$pr_title' does not follow the required naming convention."
            exit 1
          fi

      - name: Post a comment on failure
        if: failure()
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          gh pr review ${{ github.event.pull_request.number }} --request-changes --body "PR title '$pr_title' does not follow the required naming convention. Please rename your PR title to follow the required pattern (e.g., 'CREDMGR-12345 changes in workflow')."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

