name: Validate PR Title and Create Issue on Label

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    environment: STG

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate PR title
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          target_branch="${{ github.event.pull_request.base.ref }}"
          echo "PR title: $pr_title"
          echo "Target branch: $target_branch"

          if [[ "$target_branch" == "main" ]]; then
            pattern="^CM-[0-9]+ .+$"
          else
            pattern="^CREDMGR-[0-9]+ .+$"
          fi

          # Check if PR title matches the required pattern
          if [[ ! "$pr_title" =~ $pattern ]]; then
            echo "PR title '$pr_title' does not follow the required naming convention for the target branch '$target_branch'!"
            exit 1
          fi

      - name: Post a comment on failure
        if: failure()
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          target_branch="${{ github.event.pull_request.base.ref }}"
          gh pr review ${{ github.event.pull_request.number }} --request-changes --body "PR title '$pr_title' does not follow the required naming convention for the target branch '$target_branch'. Please rename your PR title to follow the required pattern (e.g., 'CM-12345 changes in workflow' for main branch or 'CREDMGR-12345 changes in workflow' for other branches)."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for 'bug' label and create issue
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels | map(.name)')
          if [[ $LABELS == *'"bug"'* ]]; then
            echo "Label 'bug' detected"
            gh issue create --title "Bug report from PR #${PR_NUMBER}" --body "This issue was automatically created because the 'bug' label was added to PR #${PR_NUMBER}. Please investigate and resolve the issue." --label "bug"
          else
            echo "Label 'bug' not detected"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
