name: Create Issue on Label 
on:
  pull_request:
    types: [opened , labeled]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        if: contains(github.event.pull_request.labels.*.name, 'bug')
        run: |
          echo "Label 'bug' detected"
          gh issue create --title "Bug report from PR #${{ github.event.pull_request.number }}" --body "This issue was automatically created because the 'bug' label was added to PR #${{ github.event.pull_request.number }}. Please investigate and resolve the issue." --label "bug"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
