name: Create Issue on Label

on:
  pull_request:
    types: [labeled]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"

      - name: Check for 'bug' label and create issue
        if: contains(github.event.pull_request.labels.*.name, 'bug')
        run: |
          echo "Label 'bug' detected"
          gh issue create --title "Bug report from PR #${{ github.event.pull_request.number }}" --body "This issue was automatically created because the 'bug' label was added to PR #${{ github.event.pull_request.number }}. Please investigate and resolve the issue." --label "bug"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
