name: Versioning Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  generate-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Next Version
        id: generate-version
        run: |
          latest_version=$(git describe --tags `git rev-list --tags --max-count=1`)
          
          # Extract major, minor, and patch numbers from the latest version tag
          regex="^([0-9]+)\.([0-9]+)\.([0-9]+)$"
          if [[ $latest_version =~ $regex ]]; then
              major="${BASH_REMATCH[1]}"
              minor="${BASH_REMATCH[2]}"
              patch="${BASH_REMATCH[3]}"
          else
              major="1"
              minor="0"
              patch="0"
          fi
          
          # Increment the patch number to generate the next version
          next_patch=$((patch + 1))
          new_version="${major}.${minor}.${next_patch}"
          
          echo "::set-output name=new_version::$new_version"
        
      - name: Use the New Version
        run: |
          echo "Next version is ${{ steps.generate-version.outputs.new_version }}"
