name: PR Build, Test, and Approval

on:
  pull_request:
    branches: ["main", "release"]

jobs:
  review-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

    #  - name: Build with Maven
     #   run: mvn -B package --file pom.xml

      - name: Test
        id: test
        run: |
          mvn --batch-mode test || echo "Tests failed"
        continue-on-error: true

      - name: Capture test result
        id: test-result
        run: echo "Test outcome:${{ steps.test.outcome }}" > $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Check if unit tests passed
        run: |
          if [ "${{ steps.test.outcome }}" == "success" ]; then
            echo "Unit tests passed, approving PR."
            gh pr review ${{ github.event.pull_request.number }} --approve --body "All checks passed. Approving the PR."
          else
            echo "Unit tests failed, requesting changes."
            gh pr review ${{ github.event.pull_request.number }} --request-changes --body "Some checks failed. Please review."
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
