name: PR Build, Test, and Approval

on:
  pull_request:
    branches: ["main", "release", "develop"]  

jobs:
  review-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Test
        id: run-tests
        run: mvn --batch-mode -Dmaven.test.failure=true test
        continue-on-error: true

      - name: Check test result and take action
        run: |
          if [ "${{ steps.run-tests.outcome }}" == "success" ]; then
            echo "Unit tests passed, approving PR."
            gh pr review ${{ github.event.pull_request.number }} --approve --body "All checks passed. Approving the PR."
          else
            echo "Unit tests failed, requesting changes."
            gh pr review ${{ github.event.pull_request.number }} --request-changes --body "Some checks failed. Please review."
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
