name: PR Build, Test, and Approval

on:
  pull_request:
    branches: ["main", "release"]

jobs:
  review-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Test
        id: run-tests
        run: mvn --batch-mode test
        continue-on-error: true

      - name: Check test result
        id: test-result
        run: |
          if [ "${{ steps.run-tests.outcome }}" == "success" ]; then
            echo "Test result: success" >> $GH_TOKEN
          else
            echo "Test result: failure" >> $GH_TOKEN
            exit 0
          fi

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Approve PR if tests passed
        if: env.test_result == 'success'
        run: |
          echo "Unit tests passed, approving PR."
          gh pr review ${{ github.event.pull_request.number }} --approve --body "All checks passed. Approving the PR."
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Request changes if tests failed
        if: env.test_result == 'failure'
        run: |
          echo "Unit tests failed, requesting changes."
          gh pr review ${{ github.event.pull_request.number }} --request-changes --body "Some checks failed. Please review."
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
