name: Create and Publish Release Notes

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create_release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Draft and Publish Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
